---
workflows:
  - name: test_wf
    init:
      source_host:
        value: 10.10.10.89 
      target_host:
        value: 127.0.0.1
    tasks:
      #- scan:
      #    - src_portscan
      #    - tgt_portscan
      - src_portscan
      - tgt_portscan
      - portmap

