---
workflows:
  - name: test_wf
    init:
      source_host:
        value: 127.0.0.1
      source_shallow_scan:
        value: True
      target_host:
        value: 127.0.0.1
      target_shallow_scan:
        value: True
    tasks:
      #- scan:
      #    - src_portscan
      #    - tgt_portscan
      - src_portscan
      - tgt_portscan
      - portmap

