---
workflows:
  - name: test_wf
    init:
      source_host:
        value: 192.168.121.237 
      target_host:
        value: 127.0.0.1
      container_name:
        value: "test"
      storage_path: 
        value: /tmp/test
      ssh_options: 
        value: "User=root"
      excluded_paths:
        value:
          - /tmp
          - /dev
          - /proc
    tasks:
      #- scan:
      #    - src_portscan
      #    - tgt_portscan
      #- src_portscan
      #- tgt_portscan
      #- portmap
      # - delete_container
      #- delete_container_data
      - rsync

